services:
  db:
    image: postgres:14.5
    volumes:
      - ./data/db/${DB_NAME}:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
  
  web:
    build: .
    ports:
      - "${FASTAPI_PORT}:5000"
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
